import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"; // Assuming Shadcn setup
import SessionProviderWrapper from "@/components/session-provider-wrapper"; // See below
import Header from "@/components/layout/header"; // Create this component
import Footer from "@/components/layout/footer"; // Create this component
import { Toaster } from "@/components/ui/sonner"; // From Shadcn

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My E-commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        {/* SessionProvider needs to be in a Client Component */}
        <SessionProviderWrapper>
          {/* ThemeProvider for Shadcn dark/light mode */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col min-h-screen">
              <Header /> {/* Your site header */}
              <main className="flex-grow container mx-auto px-4 py-8">
                {children}
              </main>
              <Footer /> {/* Your site footer */}
            </div>
            <Toaster /> {/* For Shadcn toast notifications */}
          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}